Connect api
benwmx/BookStore pull request #3
Opened 2021-10-07 12:39 UTC by benwmx

# Third Milestone 🔢 
in this pull request I added the following changes :

* Added select tag for categories.
* Added categories to the store & a default list.
* Added redux-thunk as middleware to handle API/app interactions.
* Refactored remove book feature to persist your changes in the server.
* Refactored add book feature to persist your changes in the server.

2021-10-07 13:44 UTC, dasileker requested changes
### **Hi @benwmx,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 13:44 UTC, dasileker commented on src/redux/books/books.js
> +};
- [x] Nice job on the `add & remove` the books from the `API`, but as the requirements say that you need to use `middleware to make async request` not `fetch` method.

![mpmpm](https://user-images.githubusercontent.com/61562626/136396423-7187ee4f-d740-41a5-9322-6ce42f7c3485.jpeg)

2021-10-07 14:01 UTC, benwmx commented on src/redux/books/books.js
> +};
what do you mean exactly?
I'm using the redux-thunk library which is a Middleware that extends the store's abilities and lets you write async logic that interacts with the store.
https://github.com/benwmx/BookStore/blob/398bc58e8d11921b3ca9f01964e7ce97da9e9d5f/src/redux/configureStore.js#L12

and the two functions  Add/Remove, are action creators that return a function ( that can take dispatch & state as arguments )that is executed by redux-thunk, this allows us to do async API calls and any other side effects.
so these two functions are middleware.
https://github.com/benwmx/BookStore/blob/398bc58e8d11921b3ca9f01964e7ce97da9e9d5f/src/redux/books/books.js#L25-L48

2021-10-07 16:24 UTC, rukundoeric approved these changes
Hi @benwmx,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-07 16:39 UTC, benwmx commented
Thank you @rukundoeric for your time reviewing my code.

2021-10-07 16:39 UTC, merged

2021-10-14 15:52 UTC, bellom commented
Hello 👋,

This is an additional review as a result of the second opinion request.

I'm sorry this took longer than it should, it totally passed by and got lost in the queue, and also because it was approved already the priority went low.

You're right, you can use redux-thunk.

Keep rocking 🚀!